import { useEffect, useState } from "react"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Loader2, FileText } from "lucide-react"

interface ReportInfo {
  name: string
  path: string
  type: "csv" | "md"
  description: string
}

const REPORTS: ReportInfo[] = [
  { name: "Walk-Forward OOS", path: "/reports/walk_forward.csv", type: "csv", description: "Out-of-sample Sharpe / return / DD per strategy." },
  { name: "Regime Tests", path: "/reports/regime_tests.csv", type: "csv", description: "Strategy performance across 2018 crash / 2020 COVID / 2022 chop / full sample." },
  { name: "Regime Summary (Markdown)", path: "/reports/regime_tests.md", type: "md", description: "Same data as CSV, formatted as a markdown table." },
]

export default function ReportsPanel() {
  const [content, setContent] = useState<string>("")
  const [loading, setLoading] = useState(false)
  const [activeReport, setActiveReport] = useState<ReportInfo | null>(null)
  const [error, setError] = useState<string | null>(null)

  const loadReport = async (r: ReportInfo) => {
    setLoading(true)
    setError(null)
    setActiveReport(r)
    try {
      const res = await fetch(r.path)
      if (!res.ok) throw new Error(`${res.status} ${res.statusText} — run \`python3 scripts/run_validation.py\` first`)
      const text = await res.text()
      setContent(text)
    } catch (e: any) {
      setError(e.message)
      setContent("")
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { loadReport(REPORTS[1]) }, [])

  return (
    <div className="grid grid-cols-1 lg:grid-cols-4 gap-4">
      <Card className="lg:col-span-1">
        <CardHeader>
          <CardTitle className="text-base">Validation Reports</CardTitle>
          <CardDescription>Generated by `scripts/run_validation.py`.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-2">
          {REPORTS.map(r => (
            <button
              key={r.path}
              onClick={() => loadReport(r)}
              className={`block w-full text-left p-3 rounded-md border hover:bg-accent ${activeReport?.path === r.path ? "bg-accent" : ""}`}
            >
              <div className="flex items-center gap-2">
                <FileText className="h-4 w-4" />
                <span className="font-medium text-sm">{r.name}</span>
                <Badge variant="outline" className="ml-auto">{r.type}</Badge>
              </div>
              <p className="text-xs text-muted-foreground mt-1">{r.description}</p>
            </button>
          ))}
        </CardContent>
      </Card>

      <Card className="lg:col-span-3">
        <CardHeader>
          <CardTitle>{activeReport?.name || "Pick a report"}</CardTitle>
        </CardHeader>
        <CardContent>
          {loading && <Loader2 className="h-6 w-6 animate-spin" />}
          {error && <p className="text-sm text-destructive">{error}</p>}
          {!loading && !error && content && (
            <pre className="text-xs font-mono whitespace-pre overflow-auto max-h-[600px] bg-muted/50 p-3 rounded">
              {content}
            </pre>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
